var courses = 
    [
       
    {"id": 1,
    "title": "Modern HTML &amp; CSS From The Beginning (Including Sass)",
    "instructor": "Matthew Burton",
    "price": 19.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/2153774_bef0_4.jpg"},
    {"id": 2,
    "title": "Bootstrap - Create 4 Real World Projects(Flexbox is included)",
    "instructor": "Yash Panchal",
    "price": 29.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/1572656_9b5f_5.jpg"},
    {"id": 3,
    "title": "JavaScript - The Complete Guide 2020 (Beginner + Advanced)",
    "instructor": "Maximilian Schwarzmüller",
    "price": 199.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/2508942_11d3.jpg"},
    {"id": 4,
    "title": "The Complete React Native + Hooks Course [2020 Edition]",
    "instructor": "Stephen Grider ",
    "price": 104.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/480x270/959700_8bd2_11.jpg"},
    {"id": 5,
    "title": "Get to grips with Angular 7's new and exciting features",
    "instructor": "Packt Publishing",
    "price": 134.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/2072640_248a_2.jpg"},
    {"id": 6,
    "title": "Complete Vuejs Course: Vue.js + Nuxt.js + PHP + Express.js",
    "instructor": "Elvis Ximenes",
    "price": 109.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/480x270/1173284_ffaf_3.jpg"},
    {"id": 7,
    "title": "Learn Python Programming Masterclass",
    "instructor": "Tim Buchalka's ",
    "price": 159.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/480x270/629302_8a2d_2.jpg"},
    {"id": 8,
    "title": "SQL Masterclass: SQL for Data Analytics",
    "instructor": "Start-Tech",
    "price": 199.99,
    "level": "Beginner to Advance",
    "img": "https://img-a.udemycdn.com/course/480x270/2120874_a33d.jpg"},
    {"id": 9,
    "title": "PHP for Beginners to Inventory POS Sales Project",
    "instructor": "Mohammad Faizan",
    "price": 201.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/2173272_9dd5_2.jpg"},
    {"id": 10,
    "title": "Learn Photoshop, Web Design & Profitable Freelancing",
    "instructor": "Cristian Doru Barin",
    "price": 209.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/957940_4115_3.jpg"},
    {"id": 11,
    "title": "The Complete 2020 Web Development Bootcamp",
    "instructor": "Dr. Angela Yu",
    "price": 219.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/1565838_e54e_11.jpg"},
    {"id": 12,
    "title": "The Data Science Course 2020: Complete Data Science Bootcamp",
    "instructor": "365 Careers",
    "price": 99.99,
    "level": "Advanced",
    "img": "https://img-a.udemycdn.com/course/480x270/1754098_e0df_3.jpg"},
    {"id": 13,
    "title": "iOS 11 & Swift 4 - The Complete iOS App Development Bootcamp",
    "instructor": "Dr. Angela Yu",
    "price": 16.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/1289478_5831_9.jpg"},
    {"id": 14,
    "title": "The Ultimate Guide to Game Development with Unity 2019",
    "instructor": "Jonathan Weinberger",
    "price": 139.99,
    "level": "Intermediate",
    "img": "https://img-a.udemycdn.com/course/480x270/1328572_b05d_4.jpg"},
    {"id": 15,
    "title": "After Effects - Motion Graphics & Data Visualization",
    "instructor": "Daniel Walter Scott",
    "price": 134.99,
    "level": "Beginner",
    "img": "https://img-a.udemycdn.com/course/480x270/1329786_8aa9_6.jpg"},
]

    export default courses;    